### ISSUE TITLE
Name change may have introduced typo

### ISSUE THREAD

**Issue by graphit0** [manuerwin/joplin-plugin-attache#13]
![image](https://user-images.githubusercontent.com/44114323/146268366-5064b0fd-0978-49f2-9963-5252361efac3.png)

As seen on image, now the tool menu lists the name of the plugin, not the function (replace resources). I wonder if this is expected behaviour.
It's okay, if it is but if not, may I suggest to call this line "Update attachments"?

Thanks for your work!

**Comment by manuerwin** [comment]
Thanks @graphit0 for the pickup, fixed!
